### ISSUE TITLE
User can add a trip

### ISSUE THREAD

**Issue by jennydtran** [jennydtran/final-project#1]
## 💰 Feature

User can add a trip

## 🗒️ Notes

Create a form to add a trip.

## 🖼 Wireframe
![Screen Shot 2020-12-23 at 1 07 03 PM](https://user-images.githubusercontent.com/71470231/103036996-cec12800-451f-11eb-84fc-607ed8fedbb7.png) ![Screen Shot 2020-12-23 at 12 56 03 PM](https://user-images.githubusercontent.com/71470231/103036283-41310880-451e-11eb-9f45-d37219dd3c5b.png)

## ✅ Tasks
- [x] Build out page for view: trip list
> - [x] Style with CSS
> - [x] Add onClick property to the `Add` button
> - [x] ViewSwap to modal for form
_For now ignore all other buttons (like the menu button in corner)_

- [x] Build out modal for form (overlay)
> - [x] Build form
> - [x] Style with CSS
> - [x] Don't forget: Number of nights should be calculated

- [x] Add eventHandlers to listen for value changes in the input fields.
- [x] Add eventHandler for submit button
- [x] Submit, should add trip details to database

Changes for pull request
- [x] Fix db-import.bash file
- [x] Add some Bootstrap classes mentioned in the pull request.
- [x] Take out unnecessary custom CSS code
- [x] Add staticMiddleware
- [x] Remove comments
- [x] Put own styles AFTER external styles
