### ISSUE TITLE
Users can sign up

### ISSUE THREAD

**Issue by jennydtran** [jennydtran/final-project#10]
## 💰 Feature

User can sign up

## 🗒️ Notes
-- Username cannot already be in database, username will have certain character constraints, password will have constraints (at least 8 characters, 1 number, etc)

## 🖼 Wireframe

![Screen Shot 2020-12-23 at 2 48 26 PM](https://user-images.githubusercontent.com/71470231/103042279-edc6b680-452d-11eb-8275-b2c12b4006fd.png)

## ✅ Tasks
- [x]  Create post route
> - [x]  Hash password with argon2
> - [x]  Sql query: insert into users table
> - [x]  Test httpie route, make sure all is good

- [x]  Build out Sign Up page 
> - [x]  Eventhandler onChange to listen to inputs
> - [x]  Inputs are required fields (username and password)
> - [x]  Username has to have 6 characters minimum allowing only certain characters (don't want (,), . , + etc in username)
> - [x]  Password has to have 8 characters minimum, 1 lowercase, 1 uppercase, etc
> - [x]  Next button should check inputs, if it's good, next form input is shown
> - [x]  Password visibility can be toggled on/off.
> - [x]  Indicator circles should change with steps
- [x]  Submit has to make sure that all inputs are good to go
- [x]  Use fetch post; post user object
