### ISSUE TITLE
User can sign in

### ISSUE THREAD

**Issue by jennydtran** [jennydtran/final-project#11]
## 💰 Feature

User can sign in 

## 🗒️ Notes

-- Use 

## 🖼 Wireframe

![Screen Shot 2020-12-23 at 2 49 10 PM](https://user-images.githubusercontent.com/71470231/103042307-0c2cb200-452e-11eb-8856-cdff262e1afc.png)

## ✅ Tasks
- [x]  Create post route for sign-in
> - [x]  Sql query: select username and hashedPassword
> - [x]  Use argon2.verify > match password to hashedpassword; throw error if passwords don't match with "invalid login"
> - [x]  If all good, respond with payload object
> - [x]  Test httpie route, make sure all is good
> - [x]  Include authorization middleware

- [x]  Build out Sign In page
> - [x]  Make a hash route for Sign in 
> - [x]  Inputs are required fields (username and password)

- [x]  Submit has to make sure that all inputs are good to go
- [x]  Use fetch post; post user object 
- [x]  If error, show error message of "Invalid login"
- [x] Go back into triphome page to edit the placeholder "username" info
