### ISSUE TITLE
User can sign out

### ISSUE THREAD

**Issue by jennydtran** [jennydtran/final-project#12]
## 💰 Feature

User can sign out

## 🗒️ Notes

-- Sign out will remove token from storage. For now, not following figma. It will be a simple signout icon.

## 🖼 Wireframe

![Screen Shot 2020-12-23 at 2 50 32 PM](https://user-images.githubusercontent.com/71470231/103042371-3aaa8d00-452e-11eb-83f0-592afa27fc9f.png)

## ✅ Tasks
- [x] Edit the navigation bar to have a signout icon rather than the ellipse menu icon
- [x] Add a click eventHandler on the icon
- [x]  Add a return null `if this.context user === null` for componentDidMount so prevent fetch calls
