### ISSUE TITLE
User can delete a to-do entry

### ISSUE THREAD

**Issue by jennydtran** [jennydtran/final-project#14]
## 💰 Feature

User can delete a to-do entry

## 🗒️ Notes

-- A simple delete for items on the todo list. Since it's not a big deal to delete a todo item, it doesn't need a confirmation to delete.

## 🖼 Wireframe

![Screen Shot 2020-12-23 at 2 35 55 PM](https://user-images.githubusercontent.com/71470231/103041763-354c4300-452c-11eb-9b05-522d613528c6.png)

## ✅ Tasks
- [x] Create a delete route to delete a todo
- [x] Test route to see if it works 
- [x] Add onclick eventlistener to the delete icon
- [x] handclick delete: fetch with delete method
- [x] Have the todo, get sliced/removed from the array
