### ISSUE TITLE
User can view trip list

### ISSUE THREAD

**Issue by jennydtran** [jennydtran/final-project#2]
## 💰 Feature

User can view the list of trips added.

## 🗒️ Notes

-- Figure out how to style the date under the Trip name.

## 🖼 Wireframe

![Screen Shot 2020-12-23 at 12 56 09 PM](https://user-images.githubusercontent.com/71470231/103036628-0da2ae00-451f-11eb-88f8-166778ef5ec1.png)

## ✅ Tasks
HTML/CSS
- [x] Build a placeholder div for Trip Entries
- [x] Style with CSS
- [x] Icons should be clickable
- [x] Added if else statement. If tripEntries is empty, messages should appear. If not, entries should appear.
- [x] Replace placeholders with trip entry from available from database.
- [x] Be able to convert the date into "Month Year" from departure date

React
- [x] Use HTTPie to connect to server to make sure trip details can be retrieved from database
- [x] When a trip is added, make sure it renders an entry and is added to the list

PR changes
- [x] Change div into button
- [x] Take out props stored in state
