### ISSUE TITLE
User can check off a to-do item

### ISSUE THREAD

**Issue by jennydtran** [jennydtran/final-project#24]
## 💰 Feature

User can toggle completed/incomplete for a to-do item.

## 🗒️ Notes

-- Renders the todo summary on the trip page as well.

## 🖼 Wireframe

![Screen Shot 2020-12-23 at 2 35 55 PM](https://user-images.githubusercontent.com/71470231/103041763-354c4300-452c-11eb-9b05-522d613528c6.png)

## ✅ Tasks
Backend
- [x] Use 'Patch' request to server to update 'completed' for a task in the todo table (todoId will be required, and a boolean value for 'completed')
- [x] Check to see if the checkbox gets updated on the todo page

Frontend
- [x] Create an `onClick` event handler for buttons
- [x] When item is completed, checkbox is replaced by checkmark icon
- [x] fetch: method = `Patch`
- [x] setState of completed to true

- [x] Have parent state change when child component changes

PR changes
- [x] use clientError for consistency
- [x] Remove hooks
- [x] Copy eggs into the egg carton
- [x] Update and use fetch() in the updateComplete() function
