### ISSUE TITLE
User can view todo summary on trip snapshot page

### ISSUE THREAD

**Issue by jennydtran** [jennydtran/final-project#26]
## 💰 Feature

User can view todo summary on trip summary page. Gives the user a preview on how many items are completed on the todo list for the trip.

## 🗒️ Notes

-- Will use count() for sql.

## 🖼 Wireframe

![Screen Shot 2020-12-23 at 1 29 02 PM](https://user-images.githubusercontent.com/71470231/103038262-ddf5a500-4522-11eb-91d0-d941f1917f14.png)

![Screen Shot 2020-12-23 at 3 02 00 PM](https://user-images.githubusercontent.com/71470231/103042866-d4266e80-452f-11eb-9094-14b4135005f9.png)

## ✅ Tasks
Backend
- [x] SQL use count() to get number of task completed (true) on the table where tripId = current tripId
> - [x] **note: Number of total tasks can be found by using todoArray.length.

Frontend
- [x] Fetch: get method to server to obtain todo list from database
- [x] Fetch: get method to server to obtain number of completed task
- [x] If todo list is empty, render a "start prepping message"
- [x] Else message with number of items completed will be shown instead
