### ISSUE TITLE
User can view a trip's main summary

### ISSUE THREAD

**Issue by jennydtran** [jennydtran/final-project#3]
## 💰 Feature

User can view a trip's main summary

## 🗒️ Notes

-- First work on backend, then frontend. Create routes first.

## 🖼 Wireframe

![Screen Shot 2020-12-23 at 1 29 02 PM](https://user-images.githubusercontent.com/71470231/103038262-ddf5a500-4522-11eb-91d0-d941f1917f14.png)

![Screen Shot 2020-12-23 at 3 02 00 PM](https://user-images.githubusercontent.com/71470231/103042866-d4266e80-452f-11eb-9094-14b4135005f9.png)
## ✅ Tasks
Backend
- [x] Use HTTPie and make a get request to server to retrieve data for only 1 trip
> - [x] Create a path that includes path parameters 

Frontend
Create TripHome page with placeholders
- [x] User React and style with Bootstrap/CSS
> - [x] Nav bar and first top div section first
- [x] Middle section with the "To Do list summary" can have placeholder information for now. That will be a different feature.
- [x] Create buttons to navigate to other pages. Don't include a link for now but make it clickable.

- [x] Put all svgs into it's own separate components folder 

- [x] According to which trip was clicked on from the home page, only that information for the trip should be displayed
> - [x] Should navigate to the TripHome with correct hash route 
- [x] Fix layout of page...
