### ISSUE TITLE
User can add entry to to-do list

### ISSUE THREAD

**Issue by jennydtran** [jennydtran/final-project#4]
## 💰 Feature

User can add a to-do

## 🗒️ Notes

-- When To-Do is added, it should correlate with tripId >> Only added specifically for that trip.
-- When item is posted after clicking "add" on frontend, database should be added. Nothing should be rendered yet. That is the next feature!!!

## 🖼 Wireframe

![Screen Shot 2020-12-23 at 2 35 55 PM](https://user-images.githubusercontent.com/71470231/103041763-354c4300-452c-11eb-9b05-522d613528c6.png)

## ✅ Tasks
Backend
- [x] Use HTTPie and make a post request to server to add task and 'isCompleted' to database
- [x] Create a path that includes path parameters {tripId + todo page}

Frontend
Create Todo page
- [x] Add a hash route to navigate to the todo page
- [x] User React and style with Bootstrap/CSS
> - [x] Nav bar and first top div section first
> - [x] Form at the bottom
> - [x] Create the look of the footer for the slide up menu but doesn't work yet. That is a different feature.
  - [x] For form, when user clicks Add, database should get updated. Nothing else happens. Rendering the task on the page is the next feature.
  - [x] State should begin with empty todos array and when user clicks Add, 
todo item is added to new array, setState of todos array to new array

PR changes
> - [x] Have each screen fetch information that's needed. Use fetch to get the trip info.
