### ISSUE TITLE
User can view to-do list

### ISSUE THREAD

**Issue by jennydtran** [jennydtran/final-project#5]
## 💰 Feature

User can view to-do list right after a to-do is added.

## 🗒️ Notes

-- For this feature, to-do can be checked off, but nothing is sent to the server to the database. That is the next feature.

## 🖼 Wireframe

![Screen Shot 2020-12-23 at 2 35 55 PM](https://user-images.githubusercontent.com/71470231/103041763-354c4300-452c-11eb-9b05-522d613528c6.png)

## ✅ Tasks
Backend
- [x] Test with HTTPie to make a get request to the server to grab todo array for trip

Front
- [x] Build out the list of todos
- [x] Style with CSS/bootstrap
- [x] When component mounts, make an api call to retrieve todo list from database
- [x] Test frontend by adding another item to the list. Item should be added and rendered.
