### ISSUE TITLE
User can add a traveler

### ISSUE THREAD

**Issue by jennydtran** [jennydtran/final-project#6]
## 💰 Feature

User can add a traveler to travelers list

## 🗒️ Notes

-- If travelers list is empty form/modal should be the first thing the user sees

## 🖼 Wireframe

![Screen Shot 2020-12-23 at 2 41 28 PM](https://user-images.githubusercontent.com/71470231/103042048-1a2e0300-452d-11eb-9e43-023dc2f55758.png)

## ✅ Tasks
- [x] Use HTTPie to make a get request to server to get the list of travelers
- [x] Use HTTPie to make a post request to server to post to travelers table
- [x] Create a path that includes path parameters {tripId + traveler page}

Create Todo page
- [x] Add a hash route to navigate to the travelers page
- [x] Use React and style with Bootstrap/CSS
> - [x] Nav bar and first top div section first **** make this into a component, separate file
> - [x] Create a modal and form to add traveler
> - [x] Create the look of the footer for the slide up menu but doesn't work yet. That is a different feature.   **** make a component, separate file
  - [x] For form, when user clicks Add, database should get updated. Nothing else happens. Rendering traveler items on the page is the next feature.
  - [x] State should begin with empty travelers array and when user clicks Add, 
traveler item is added to new array, setState of todos array to new array
