### ISSUE TITLE
User can view travelers list 

### ISSUE THREAD

**Issue by jennydtran** [jennydtran/final-project#7]
## 💰 Feature

User can view travelers list

## 🗒️ Notes

-- Get the travelers list during componentDidMount

## 🖼 Wireframe

![Screen Shot 2020-12-23 at 2 41 38 PM](https://user-images.githubusercontent.com/71470231/103042061-2a45e280-452d-11eb-9991-317059937641.png)

## ✅ Tasks
- [x] Build out list
> - [x] Use a table  (similiar to ul)
> - [x] Each traveler is in the tbody with tr, td elements
- [x] Style with CSS/Bootstrap
- [x] Test by adding and see if traveler item renders
